# Generated by Django 3.0.7 on 2020-07-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('usd', models.CharField(max_length=255)),
                ('eur', models.CharField(max_length=255)),
                ('jpy', models.CharField(max_length=255)),
                ('cny', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CNY',
        ),
        migrations.DeleteModel(
            name='EUR',
        ),
        migrations.DeleteModel(
            name='JPY',
        ),
        migrations.DeleteModel(
            name='USD',
        ),
    ]
